name: Waka Readme Backup

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: '30 06 * * *' # Runs at 12am IST

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          SECTION_NAME: waka0
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          SHOW_TOTAL: true
          #LANGUAGE_COUNT: 10

