name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: '25 08, * * *' # Runs at 12am IST

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: infinitel8p/waka-readme-stats@master #anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SYMBOL_VERSION: 2
          COMMIT_EMAIL: 50703696+infinitel8p@users.noreply.github.com
          COMMIT_USERNAME: "infinitel8p"
          SHOW_UPDATED_DATE: true
          SHOW_LANGUAGE_PER_REPO: true
          SHOW_COMMIT: true
          SHOW_DAYS_OF_WEEK: true
          SHOW_EDITORS: true
          SHOW_TIMEZONE: true
          SHOW_PROFILE_VIEWS: false
          SHOW_TOTAL_CODE_TIME: false
          SHOW_LINES_OF_CODE: false
          SHOW_OS: false
          SHOW_PROJECTS: false
          SHOW_LOC_CHART: false
          SHOW_SHORT_INFO: false
